name: afcn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - cython
  - pysam
  - joblib
  - tqdm
  - lmfit
  - scikit-learn
  - pytest
  - pip
  - pip:
    - argparse
